import os

RUBYHAS_HQ_STORAGE = 26
RUBYHAS_WAREHOUSE = 23
AURATE_WAREHOUSE = 4
AURATE_HQ_STORAGE = 3
AURATE_STORAGE_ZONE = 3
AURATE_OUTPUT_ZONE = 2
COMPANY = 1
PRODUCTION = 9
FULFIL_API_URL = os.environ.get('FULFIL_API_ENDPOINT')
