import os

RUBYHAS_HQ_STORAGE = 26
RUBYHAS_WAREHOUSE = 23
AURATE_WAREHOUSE = 4
AURATE_HQ_STORAGE = 3
AURATE_STORAGE_ZONE = 3
AURATE_OUTPUT_ZONE = 2
COMPANY = 1
USD = 172
PRODUCTION = 9
FULFIL_API_URL = os.environ.get('FULFIL_API_ENDPOINT')
EASYPOST_API_KEY = os.environ.get('EASYPOST_API_KEY')
EASYPOST_URL = 'https://api.easypost.com/v2/shipments'

WAREHOUSE_TO_STORAGE = {
    RUBYHAS_WAREHOUSE: RUBYHAS_HQ_STORAGE,
    AURATE_WAREHOUSE: AURATE_HQ_STORAGE,
}

